# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/media/default.png', upload_to='/media/gallery/')),
                ('caption', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
