# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_data',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='/root/navmo/media/gallery/'),
        ),
    ]
