# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_results_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='topper_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=120)),
                ('group', models.CharField(blank=True, choices=[('gamma', 'gamma'), ('alpha', 'alpha')], max_length=120)),
            ],
        ),
    ]
