# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20161213_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=120)),
                ('group', models.CharField(blank=True, choices=[('alpha', 'alpha'), ('beta', 'beta'), ('thetha', 'thetha'), ('gamma', 'gamma')], max_length=120)),
                ('current_round', models.CharField(blank=True, choices=[('First-Round', 'First-Round'), ('Semi-Finals', 'Semi-Finals'), ('Finals', 'Finals')], max_length=120, null=True)),
                ('level', models.CharField(blank=True, choices=[('alpha', 'alpha'), ('beta1', 'beta1'), ('beta2', 'beta2'), ('beta3', 'beta4'), ('beta4', 'beta4'), ('beta5', 'beta5'), ('MM-1', 'MM-1'), ('MM-2', 'MM-2'), ('MM-3', 'MM-3'), ('MM-4', 'MM-4'), ('MM-4', 'MM-4'), ('thetha-1', 'thetha-1'), ('thetha-2', 'thetha-2')], max_length=120)),
                ('center', models.CharField(blank=True, choices=[('NH Goel', 'NH Goel'), ('ICIS', 'ICIS')], max_length=120)),
                ('marks_first', models.FloatField(default=0.0)),
                ('time_first', models.FloatField(default=0.0)),
                ('npi_first', models.FloatField(default=0.0)),
                ('marks_semi', models.FloatField(default=0.0)),
                ('time_semi', models.FloatField(default=0.0)),
                ('npi_semi', models.FloatField(default=0.0)),
                ('marks_final', models.FloatField(default=0.0)),
                ('time_final', models.FloatField(default=0.0)),
                ('npi_final', models.FloatField(default=0.0)),
            ],
        ),
    ]
