# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20161214_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks_data',
            name='level',
            field=models.CharField(blank=True, choices=[('alpha', 'alpha'), ('beta1', 'beta1'), ('beta2', 'beta2'), ('beta3', 'beta3'), ('beta4', 'beta4'), ('beta5', 'beta5'), ('MM-1', 'MM-1'), ('MM-2', 'MM-2'), ('MM-3', 'MM-3'), ('MM-4', 'MM-4'), ('MM-5', 'MM-5'), ('thetha-1', 'thetha-1'), ('thetha-2', 'thetha-2')], max_length=120),
        ),
    ]
