# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20161214_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks_data',
            name='center',
            field=models.CharField(blank=True, choices=[('NH Goel', 'NH Goel'), ('ICIS', 'ICIS'), ('MPE Raipur', 'MPE Raipur')], default='NH Goel', max_length=120),
        ),
    ]
