# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20161215_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks_data',
            name='center',
            field=models.CharField(blank=True, choices=[('NH Goel', 'NH Goel'), ('MPE Odisha', 'MPE Odisha'), ('MPE Ranchi', 'MPE Ranchi'), ('ICIS', 'ICIS'), ('MPE Raipur', 'MPE Raipur'), ('B K Birla', 'B K Birla'), ('NPPS , Rajnandgaon', 'NPPS , Rajnandgaon'), ('NBIS , Rajnandgaon', 'NBIS , Rajnandgaon'), ('Atelier School Magarpatta', 'Atelier School Magarpatta'), ('MPE KOTA', 'MPE KOTA'), ('MPE AMRAVATI', 'MPE AMRAVATI')], default='NH Goel', max_length=120),
        ),
        migrations.AlterField(
            model_name='marks_data',
            name='level',
            field=models.CharField(blank=True, choices=[('alpha', 'alpha'), ('alpha1', 'alpha1'), ('alpha2', 'alpha2'), ('beta1', 'beta1'), ('beta2', 'beta2'), ('beta3', 'beta3'), ('beta4', 'beta4'), ('beta5', 'beta5'), ('MM-1', 'MM-1'), ('MM-1A', 'MM-1A'), ('MM-1B', 'MM-1B'), ('MM-1C', 'MM-1C'), ('MM-2', 'MM-2'), ('MM-3', 'MM-3'), ('MM-4', 'MM-4'), ('MM-5', 'MM-5'), ('thetha-1', 'thetha-1'), ('thetha-2', 'thetha-2')], max_length=120),
        ),
        migrations.AlterField(
            model_name='topper_data',
            name='center',
            field=models.CharField(blank=True, choices=[('NH Goel', 'NH Goel'), ('MPE Odisha', 'MPE Odisha'), ('MPE Ranchi', 'MPE Ranchi'), ('ICIS', 'ICIS'), ('MPE Raipur', 'MPE Raipur'), ('B K Birla', 'B K Birla'), ('NPPS , Rajnandgaon', 'NPPS , Rajnandgaon'), ('NBIS , Rajnandgaon', 'NBIS , Rajnandgaon'), ('Atelier School Magarpatta', 'Atelier School Magarpatta'), ('MPE KOTA', 'MPE KOTA'), ('MPE AMRAVATI', 'MPE AMRAVATI')], default='NH Goel', max_length=120),
        ),
        migrations.AlterField(
            model_name='topper_data',
            name='medal',
            field=models.CharField(choices=[('School Gold Medal', 'School Gold Medal '), ('School Silver Medal ', 'School Silver Medal '), ('School Bronze Medal ', 'School Bronze Medal ')], max_length=120, null=True),
        ),
    ]
