# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_keys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KEYS',
            new_name='keys_data',
        ),
    ]
