# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20170106_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=120)),
                ('group', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(blank=True, max_length=120)),
                ('centre_rank', models.IntegerField(default=0)),
                ('national_level_rank', models.IntegerField(default=0)),
                ('national_group_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='keys_data',
        ),
        migrations.AlterField(
            model_name='marks_data',
            name='center',
            field=models.CharField(blank=True, choices=[('NH Goel', 'NH Goel'), ('MPE Odisha', 'MPE Odisha'), ('MPE Ranchi', 'MPE Ranchi'), ('ICIS', 'ICIS'), ('MPE Raipur', 'MPE Raipur'), ('B K Birla', 'B K Birla'), ('NPPS , Rajnandgaon', 'NPPS , Rajnandgaon'), ('NBIS , Rajnandgaon', 'NBIS , Rajnandgaon'), ('Atelier School Magarpatta', 'Atelier School Magarpatta'), ('MPE KOTA', 'MPE KOTA'), ('MPE AMRAVATI', 'MPE AMRAVATI'), ('MPE KHARADI', 'MPE KHARADI')], default='NH Goel', max_length=120),
        ),
        migrations.AlterField(
            model_name='topper_data',
            name='center',
            field=models.CharField(blank=True, choices=[('NH Goel', 'NH Goel'), ('MPE Odisha', 'MPE Odisha'), ('MPE Ranchi', 'MPE Ranchi'), ('ICIS', 'ICIS'), ('MPE Raipur', 'MPE Raipur'), ('B K Birla', 'B K Birla'), ('NPPS , Rajnandgaon', 'NPPS , Rajnandgaon'), ('NBIS , Rajnandgaon', 'NBIS , Rajnandgaon'), ('Atelier School Magarpatta', 'Atelier School Magarpatta'), ('MPE KOTA', 'MPE KOTA'), ('MPE AMRAVATI', 'MPE AMRAVATI'), ('MPE KHARADI', 'MPE KHARADI')], default='NH Goel', max_length=120),
        ),
    ]
