# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_auto_20170131_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default='/default.png', upload_to='/media/'),
        ),
    ]
