# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_reset_otp',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='password_reset_otp',
            name='otp',
            field=models.BigIntegerField(default=0),
        ),
    ]
