# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_password', '0002_auto_20161020_0403'),
        ('forgot_password', '0002_auto_20161020_0404'),
    ]

    operations = [
    ]
